### ISSUE TITLE
Segment multiple classes at the same time

### ISSUE THREAD

**Issue by vincentme** [zjuhans/cdfss#4]
Hi

I have a question about the usgae. From the code, the current approach seems only test-time adapt based on query image of mask of one class. So if my application is to few-shot segment multiple class at once. Is this doable here? 

Thanks!

**Comment by Vision-Kek** [comment]
> From the code, the current approach seems only test-time adapt based on query image of mask of one class.

Yes.

> So if my application is to few-shot segment multiple class at once. Is this doable here? Is this doable here?

That's a valid question which I also think is worth addressing, but since previous work did only binary segmentation, I kept the single-class segmentation setting for this work.

One option to realize multi-class segmentation:
For n classes of interest, split your support GT in n binary support masks and then do n subsequent predictions. Keep input query and support image the same and only change the support mask in each prediction.

**Comment by vincentme** [comment]
Got it, thanks!
